### ISSUE TITLE
Getting tons of errors with Xcode8

### ISSUE THREAD

**Issue by alapergola** [kazuhiro4949/StringStylizer#8]
Seemed like this branch was already Swift3 capable, isn't it?

**Comment by kazuhiro4949** [comment]
Sorry😨 I'll check later.

**Comment by kazuhiro4949** [comment]
I made a pull-request for supporting latest xcode8.0, swift3.0
https://github.com/kazuhiro4949/StringStylizer/pull/9

**Comment by kazuhiro4949** [comment]
@alapergola
I'm sorry to keep you waiting. I have committed code to support latest swift 3.0. You can install it with Cocoapods or Carthage. I have updated README too.

https://github.com/kazuhiro4949/StringStylizer/commit/c185a9f3ae60207ddcec2d8e6df336404bd47525

**Comment by alapergola** [comment]
Thanks man! Trying right now.
Appreciate your effort 👏🏻👏🏻
